### ISSUE TITLE
MacOS install process

### ISSUE THREAD

**Issue by avi-gitkraken** [gitkraken/gk-cli#2]
**Is your feature request related to a problem? Please describe.**
After installing the CLI on MacOS and moving it to `/usr/local/bin/`, I get the following error when running `gk`:

`zsh: command not found: gitk`

**Describe the solution you'd like**
The readme should probably be updated with more information about installing on MacOS.

**Describe alternatives you've considered**
Eventually, it would be great to be able to install this using HomeBrew!

Happy to provide any other information you need.

**Comment by zawata** [comment]
I was having this same problem on manjaro.

It's actually caused by oh-my-zsh(or zplug in my case). The default git plugin adds an alias called `gk` and aliases resolve before executables.

The spcific alias: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh#L215

to fix this you could either disable the plugin(I wasn't using it anyways) or rename the executable to something else that doesn't conflict.

**Comment by hernanvicente** [comment]
I wanted to continue using the plugin, so I decided just to put `unalias gk` at the bottom of my `~/.zshrc` file, and it just worked :)
