### ISSUE TITLE
[BUG] Unable to create a cloud workspace for our company GitHub Enterprise Server

### ISSUE THREAD

**Issue by LastStarDust** [gitkraken/gk-cli#48]
### Description

1. Try to create a cloud workspace for GitHub Enterprise Server
2. The workspace is created but no repositories can be added
3. The following error is displayed in the main windows: *We are having trouble connecting to GitHub Enterprise Server. Please check your integration settings for GitHub Enterprise Server to access this workspace.*
4. The following error is displayed as a popup window: *Gitkraken GitHub Enterprice server failed to initialize {"error": "Not Found"}*

I confirmed that I can manually clone, pull, push from the single repositories (I do it on a daily basis). It is just the cloud workspace feature which is not working.

If there is any additional setting that our IT department need to do on the GitHub side, please let us know.

### GitKraken CLI Version

9.13.0

### OS Version

- OS: Windows 10 Pro
- Version: 10.0.19045 Build 19045
- Laptop: Dell XPS 15 9510 amd64

### Git Version

git version 2.44.0.windows.1

### Logs, Screenshots, Screen Captures, URLs, etc

![image](https://github.com/gitkraken/gk-cli/assets/8758474/243e23b1-3799-405a-b664-2a3b8b07f00c)
![image](https://github.com/gitkraken/gk-cli/assets/8758474/2b787445-d3f3-4a4e-9734-8f8ab5c868d6)

**Comment by jkelroy** [comment]
Hello @LastStarDust, as this is for GitKraken Client, and not GitKraken CLI, please reach out to the team [here](https://help.gitkraken.com/gitkraken-client/contact-support/) (or by selecting _support_ in the bottom right of GitKraken Client) to troubleshoot this further. 

I am not aware of any existing similar issues but to ensure the issue is not simply the integration connection, can you please quickly try disconnecting and reconnecting the GitHub Enterprise Server integration? If this does not help, please include the extended logs when sending us an email:

- Close GitKraken
- Rename or move the \logs folder under C:\Users\{user}\AppData\Roaming\.gitkraken\logs
- Start GitKraken from the CLI using _gitkraken -d SILLY_
- Reproduce the error
- Send over the \logs folder
