### ISSUE TITLE
[BUG] GITHUB STUDENT PACK

### ISSUE THREAD

**Issue by FFUV** [gitkraken/gk-cli#54]
### Description

Tried to get pro with github student pack used my github account has student stuff yet still dont have pro >:(

### GitKraken CLI Version

1.0.6

### OS Version

MacOS Big Sur

**Comment by jkelroy** [comment]
Hello @FFUV, this issue is not specific to the GK CLI so I will close it but you can reach out to our support team [here](https://help.gitkraken.com/gitkraken-client/contact-support/) if you continue to have issues. 

To verify your GitHub Student Developer Pack, log in again using GitHub. If this is for the GK CLI, use `gk login`. If this is for GitKraken Desktop, you can sign in from File > Sign into a different account > Sign in with GitHub.
