### ISSUE TITLE
[BUG] Error when doing any `gk.exe` command inside the GitKraken terminal on Windows

### ISSUE THREAD

**Issue by IDisposable** [gitkraken/gk-cli#8]
### Description

In the _Terminal Panel_ of GitKraken 9.6.0 (x64 64-bit), running *any* `gk` commands gives an error:

> gk version
> v1.0.7
> Error: unknown command "setCwd" for "gk"
> Run 'gk --help' for usage.

I'm current (as far as I know) on both GitKraken, and as-of today current on gk-cli as well (oops). 

### GitKraken CLI Version

1.0.7

### OS Version

Microsoft Windows [Version 10.0.22631.2048]
Processor	Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz   2.30 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	23H2
OS build	22631.2048
Experience	Windows Feature Experience Pack 1000.22658.1000.0

### Git Version

git version 2.41.0.windows.2

**Comment by IDisposable** [comment]
Note: running from a plain command prompt does NOT give the error message, just from within the GitKraken Terminal Panel

**Comment by sergiolms** [comment]
Hello! Thanks for using GitKraken CLI!

This is related to a name conflict with `gk` and an internal `gk` command that older versions of GitKraken Client had. Updating the GitKraken Client to a newer version should fix this conflict, since that command has been renamed in the client's terminal to `gkc`.

Please update the client and let us know if that solved your problem.
